
export const IconsList = [
	{
		name: 'arrow-up-down',
		preview: 'arrow-down',
		on: 'arrow-down',
		off: 'arrow-up',
	},
	{
		name: 'arrow-left-right',
		preview: 'arrow-left',
		on: 'arrow-left',
		off: 'arrow-right',
	},
	{
		name: 'bath',
		preview: 'bath',
		on: 'bath',
		off: 'bath',
	},
	{
		name: 'champagne-glasses',
		preview: 'champagne-glasses',
		on: 'champagne-glasses',
		off: 'champagne-glasses',
	},
	{
		name: 'circle-plus',
		preview: 'circle-plus',
		on: 'circle-plus',
		off: 'circle-plus',
	},
	{
		name: 'city',
		preview: 'city',
		on: 'city',
		off: 'city',
	},
	{
		name: 'code',
		preview: 'code',
		on: 'code',
		off: 'code',
	},
	{
		name: 'computer',
		preview: 'computer',
		on: 'computer',
		off: 'computer',
	},
	{
		name: 'door',
		preview: 'door-closed',
		on: 'door-open',
		off: 'door-closed',
	},
	{
		name: 'gamepad',
		preview: 'gamepad',
		on: 'gamepad',
		off: 'gamepad',
	},
	{
		name: 'gear',
		preview: 'gear',
		on: 'gear',
		off: 'gear',
	},
	{
		name: 'lightbulb',
		preview: 'lightbulb',
		on: 'lightbulb',
		off: 'lightbulb',
	},
	{
		name: 'lock',
		preview: 'lock',
		on: 'lock',
		off: 'unlock',
	},
	{
		name: 'pen',
		preview: 'pen',
		on: 'pen',
		off: 'pen',
	},
	{
		name: 'power',
		preview: 'power-off',
		on: 'power-off',
		off: 'power-off',
	},
	{
		name: 'rocket',
		preview: 'rocket',
		on: 'rocket',
		off: 'rocket',
	},
	{
		name: 'sink',
		preview: 'sink',
		on: 'sink',
		off: 'sink',
	},
	{
		name: 'toggle',
		preview: 'toggle-off',
		on: 'toggle-on',
		off: 'toggle-off',
	},
	{
		name: 'trash-can',
		preview: 'trash-can',
		on: 'trash-can',
		off: 'trash-can',
	},
	{
		name: 'tree',
		preview: 'tree',
		on: 'tree',
		off: 'tree',
	},
	{
		name: 'traingle-exclamation',
		preview: 'triangle-exclamation',
		on: 'triangle-exclamation',
		off: 'triangle-exclamation',
	},
	{
		name: 'tv',
		preview: 'tv',
		on: 'tv',
		off: 'tv',
	},
	{
		name: 'umbrella',
		preview: 'umbrella-beach',
		on: 'umbrella-beach',
		off: 'umbrella-beach',
	},
	{
		name: 'ladder',
		preview: 'water-ladder',
		on: 'water-ladder',
		off: 'water-ladder',
	},
	{
		name: 'ArchetypesBollard',
		preview: 'ArchetypesBollard',
		on: 'ArchetypesBollard',
		off: 'ArchetypesBollard',
	},
	{
		name: 'ArchetypesCeilingRound',
		preview: 'ArchetypesCeilingRound',
		on: 'ArchetypesCeilingRound',
		off: 'ArchetypesCeilingRound',
	},
	{
		name: 'ArchetypesCeilingSquare',
		preview: 'ArchetypesCeilingSquare',
		on: 'ArchetypesCeilingSquare',
		off: 'ArchetypesCeilingSquare',
	},
	{
		name: 'ArchetypesDeskLamp',
		preview: 'ArchetypesDeskLamp',
		on: 'ArchetypesDeskLamp',
		off: 'ArchetypesDeskLamp',
	},
	{
		name: 'ArchetypesDoubleSpot',
		preview: 'ArchetypesDoubleSpot',
		on: 'ArchetypesDoubleSpot',
		off: 'ArchetypesDoubleSpot',
	},
	{
		name: 'ArchetypesFloorLantern',
		preview: 'ArchetypesFloorLantern',
		on: 'ArchetypesFloorLantern',
		off: 'ArchetypesFloorLantern',
	},
	{
		name: 'ArchetypesFloorShade',
		preview: 'ArchetypesFloorShade',
		on: 'ArchetypesFloorShade',
		off: 'ArchetypesFloorShade',
	},
	{
		name: 'ArchetypesFloorSpot',
		preview: 'ArchetypesFloorSpot',
		on: 'ArchetypesFloorSpot',
		off: 'ArchetypesFloorSpot',
	},
	{
		name: 'ArchetypesPendantLong',
		preview: 'ArchetypesPendantLong',
		on: 'ArchetypesPendantLong',
		off: 'ArchetypesPendantLong',
	},
	{
		name: 'ArchetypesPendantRound',
		preview: 'ArchetypesPendantRound',
		on: 'ArchetypesPendantRound',
		off: 'ArchetypesPendantRound',
	},
	{
		name: 'ArchetypesRecessedCeiling',
		preview: 'ArchetypesRecessedCeiling',
		on: 'ArchetypesRecessedCeiling',
		off: 'ArchetypesRecessedCeiling',
	},
	{
		name: 'ArchetypesRecessedFloor',
		preview: 'ArchetypesRecessedFloor',
		on: 'ArchetypesRecessedFloor',
		off: 'ArchetypesRecessedFloor',
	},
	{
		name: 'ArchetypesSingleSpot',
		preview: 'ArchetypesSingleSpot',
		on: 'ArchetypesSingleSpot',
		off: 'ArchetypesSingleSpot',
	},
	{
		name: 'ArchetypesTableShade',
		preview: 'ArchetypesTableShade',
		on: 'ArchetypesTableShade',
		off: 'ArchetypesTableShade',
	},
	{
		name: 'ArchetypesTableWash',
		preview: 'ArchetypesTableWash',
		on: 'ArchetypesTableWash',
		off: 'ArchetypesTableWash',
	},
	{
		name: 'ArchetypesWallLantern',
		preview: 'ArchetypesWallLantern',
		on: 'ArchetypesWallLantern',
		off: 'ArchetypesWallLantern',
	},
	{
		name: 'ArchetypesWallShade',
		preview: 'ArchetypesWallShade',
		on: 'ArchetypesWallShade',
		off: 'ArchetypesWallShade',
	},
	{
		name: 'ArchetypesWallSpot',
		preview: 'ArchetypesWallSpot',
		on: 'ArchetypesWallSpot',
		off: 'ArchetypesWallSpot',
	},
	{
		name: 'BulbCandle',
		preview: 'BulbCandle',
		on: 'BulbCandle',
		off: 'BulbCandle',
	},
	{
		name: 'BulbFlood',
		preview: 'BulbFlood',
		on: 'BulbFlood',
		off: 'BulbFlood',
	},
	{
		name: 'BulbFoh',
		preview: 'BulbFoh',
		on: 'BulbFoh',
		off: 'BulbFoh',
	},
	{
		name: 'BulbGeneralGroup',
		preview: 'BulbGeneralGroup',
		on: 'BulbGeneralGroup',
		off: 'BulbGeneralGroup',
	},
	{
		name: 'BulbGroup',
		preview: 'BulbGroup',
		on: 'BulbGroup',
		off: 'BulbGroup',
	},
	{
		name: 'BulbsClassic',
		preview: 'BulbsClassic',
		on: 'BulbsClassic',
		off: 'BulbsClassic',
	},
	{
		name: 'BulbsSpot',
		preview: 'BulbsSpot',
		on: 'BulbsSpot',
		off: 'BulbsSpot',
	},
	{
		name: 'BulbsSultan',
		preview: 'BulbsSultan',
		on: 'BulbsSultan',
		off: 'BulbsSultan',
	},
	{
		name: 'DevicesBridgesV2',
		preview: 'DevicesBridgesV2',
		on: 'DevicesBridgesV2',
		off: 'DevicesBridgesV2',
	},
	{
		name: 'DevicesDimmerswitch',
		preview: 'DevicesDimmerswitch',
		on: 'DevicesDimmerswitch',
		off: 'DevicesDimmerswitch',
	},
	{
		name: 'DevicesFriendsofhue',
		preview: 'DevicesFriendsofhue',
		on: 'DevicesFriendsofhue',
		off: 'DevicesFriendsofhue',
	},
	{
		name: 'DevicesMotionSensor',
		preview: 'DevicesMotionSensor',
		on: 'DevicesMotionSensor',
		off: 'DevicesMotionSensor',
	},
	{
		name: 'DevicesPlug',
		preview: 'DevicesPlug',
		on: 'DevicesPlug',
		off: 'DevicesPlug',
	},
	{
		name: 'DevicesTap',
		preview: 'DevicesTap',
		on: 'DevicesTap',
		off: 'DevicesTap',
	},
	{
		name: 'HeroesBloom',
		preview: 'HeroesBloom',
		on: 'HeroesBloom',
		off: 'HeroesBloom',
	},
	{
		name: 'HeroesHuego',
		preview: 'HeroesHuego',
		on: 'HeroesHuego',
		off: 'HeroesHuego',
	},
	{
		name: 'HeroesHueplay',
		preview: 'HeroesHueplay',
		on: 'HeroesHueplay',
		off: 'HeroesHueplay',
	},
	{
		name: 'HeroesIris',
		preview: 'HeroesIris',
		on: 'HeroesIris',
		off: 'HeroesIris',
	},
	{
		name: 'HeroesLightstrip',
		preview: 'HeroesLightstrip',
		on: 'HeroesLightstrip',
		off: 'HeroesLightstrip',
	},
	{
		name: 'PresetsDimmerDimdown',
		preview: 'PresetsDimmerDimdown',
		on: 'PresetsDimmerDimdown',
		off: 'PresetsDimmerDimdown',
	},
	{
		name: 'PresetsDimmerDimup',
		preview: 'PresetsDimmerDimup',
		on: 'PresetsDimmerDimup',
		off: 'PresetsDimmerDimup',
	},
	{
		name: 'RoomsAttic',
		preview: 'RoomsAttic',
		on: 'RoomsAttic',
		off: 'RoomsAttic',
	},
	{
		name: 'RoomsBalcony',
		preview: 'RoomsBalcony',
		on: 'RoomsBalcony',
		off: 'RoomsBalcony',
	},
	{
		name: 'RoomsBedroom',
		preview: 'RoomsBedroom',
		on: 'RoomsBedroom',
		off: 'RoomsBedroom',
	},
	{
		name: 'RoomsCarport',
		preview: 'RoomsCarport',
		on: 'RoomsCarport',
		off: 'RoomsCarport',
	},
	{
		name: 'RoomsCloset',
		preview: 'RoomsCloset',
		on: 'RoomsCloset',
		off: 'RoomsCloset',
	},
	{
		name: 'RoomsDining',
		preview: 'RoomsDining',
		on: 'RoomsDining',
		off: 'RoomsDining',
	},
	{
		name: 'RoomsDriveway',
		preview: 'RoomsDriveway',
		on: 'RoomsDriveway',
		off: 'RoomsDriveway',
	},
	{
		name: 'RoomsGarage',
		preview: 'RoomsGarage',
		on: 'RoomsGarage',
		off: 'RoomsGarage',
	},
	{
		name: 'RoomsGuestroom',
		preview: 'RoomsGuestroom',
		on: 'RoomsGuestroom',
		off: 'RoomsGuestroom',
	},
	{
		name: 'RoomsGym',
		preview: 'RoomsGym',
		on: 'RoomsGym',
		off: 'RoomsGym',
	},
	{
		name: 'RoomsHallway',
		preview: 'RoomsHallway',
		on: 'RoomsHallway',
		off: 'RoomsHallway',
	},
	{
		name: 'RoomsKidsbedroom',
		preview: 'RoomsKidsbedroom',
		on: 'RoomsKidsbedroom',
		off: 'RoomsKidsbedroom',
	},
	{
		name: 'RoomsLaundryroom',
		preview: 'RoomsLaundryroom',
		on: 'RoomsLaundryroom',
		off: 'RoomsLaundryroom',
	},
	{
		name: 'RoomsLiving',
		preview: 'RoomsLiving',
		on: 'RoomsLiving',
		off: 'RoomsLiving',
	},
	{
		name: 'RoomsLounge',
		preview: 'RoomsLounge',
		on: 'RoomsLounge',
		off: 'RoomsLounge',
	},
	{
		name: 'RoomsOffice',
		preview: 'RoomsOffice',
		on: 'RoomsOffice',
		off: 'RoomsOffice',
	},
	{
		name: 'RoomsOutdoor',
		preview: 'RoomsOutdoor',
		on: 'RoomsOutdoor',
		off: 'RoomsOutdoor',
	},
	{
		name: 'RoomsOutdoorSocialtime',
		preview: 'RoomsOutdoorSocialtime',
		on: 'RoomsOutdoorSocialtime',
		off: 'RoomsOutdoorSocialtime',
	},
	{
		name: 'RoutinesComingHome',
		preview: 'RoutinesComingHome',
		on: 'RoutinesComingHome',
		off: 'RoutinesComingHome',
	},
	{
		name: 'RoutinesDaytime',
		preview: 'RoutinesDaytime',
		on: 'RoutinesDaytime',
		off: 'RoutinesDaytime',
	},
	{
		name: 'RoutinesGoToSleep',
		preview: 'RoutinesGoToSleep',
		on: 'RoutinesGoToSleep',
		off: 'RoutinesGoToSleep',
	},
	{
		name: 'RoutinesHomeAway',
		preview: 'RoutinesHomeAway',
		on: 'RoutinesHomeAway',
		off: 'RoutinesHomeAway',
	},
	{
		name: 'RoutinesLeavingHome',
		preview: 'RoutinesLeavingHome',
		on: 'RoutinesLeavingHome',
		off: 'RoutinesLeavingHome',
	},
	{
		name: 'house',
		preview: 'house',
		on: 'house',
		off: 'house',
	},
	{
		name: 'RoutinesLocation',
		preview: 'RoutinesLocation',
		on: 'RoutinesLocation',
		off: 'RoutinesLocation',
	},
	{
		name: 'RoutinesNighttime',
		preview: 'RoutinesNighttime',
		on: 'RoutinesNighttime',
		off: 'RoutinesNighttime',
	},
	{
		name: 'RoutinesSunrise',
		preview: 'RoutinesSunrise',
		on: 'RoutinesSunrise',
		off: 'RoutinesSunrise',
	},
	{
		name: 'RoutinesSunset',
		preview: 'RoutinesSunset',
		on: 'RoutinesSunset',
		off: 'RoutinesSunset',
	},
	{
		name: 'RoutinesTimers',
		preview: 'RoutinesTimers',
		on: 'RoutinesTimers',
		off: 'RoutinesTimers',
	},
	{
		name: 'RoutinesWakeUp',
		preview: 'RoutinesWakeUp',
		on: 'RoutinesWakeUp',
		off: 'RoutinesWakeUp',
	},
	{
		name: 'UicontrolsMotionSensitivity',
		preview: 'UicontrolsMotionSensitivity',
		on: 'UicontrolsMotionSensitivity',
		off: 'UicontrolsMotionSensitivity',
	},
	{
		name: 'UicontrolsNoMotion',
		preview: 'UicontrolsNoMotion',
		on: 'UicontrolsNoMotion',
		off: 'UicontrolsNoMotion',
	},
	{
		name: 'temperature',
		preview: 'temperature-half',
		type: 'range',
		range: {
			0: 'temperature-empty',
			33: 'temperature-quarter',
			50: 'temperature-half',
			66: 'temperature-three-quarters',
			95: 'temperature-full',
		}
	},
	{
		name: 'battery',
		preview: 'battery-half',
		type: 'range',
		range: {
			0: 'battery-empty',
			33: 'battery-quarter',
			50: 'battery-half',
			66: 'battery-three-quarters',
			95: 'battery-full',
		}
	},
	{
		name: 'bolt',
		preview: 'bolt',
		on: 'bolt',
		off: 'bolt',
	},
	{
		name: 'speaker',
		preview: 'speaker',
		on: 'speaker',
		off: 'speaker',
	},
	{
		name: 'play',
		preview: 'play',
		on: 'play',
		off: 'play',
	},
	{
		name: 'pause',
		preview: 'pause',
		on: 'pause',
		off: 'pause',
	},
	{
		name: 'stop',
		preview: 'stop',
		on: 'stop',
		off: 'stop',
	},
	{
		name: 'music',
		preview: 'music',
		on: 'music',
		off: 'music',
	},
	{
		name: 'backward-step',
		preview: 'backward-step',
		on: 'backward-step',
		off: 'backward-step',
	},
	{
		name: 'forward-step',
		preview: 'forward-step',
		on: 'forward-step',
		off: 'forward-step',
	},
	{
		name: 'shuffle',
		preview: 'shuffle',
		on: 'shuffle',
		off: 'shuffle',
	},
	{
		name: 'repeat',
		preview: 'repeat',
		on: 'repeat',
		off: 'repeat',
	},
	{
		name: 'star',
		preview: 'star',
		on: 'star',
		off: 'star',
	},
	{
		name: 'wrench',
		preview: 'wrench',
		on: 'wrench',
		off: 'wrench',
	},
	{
		name: 'rotate',
		preview: 'rotate',
		on: 'rotate',
		off: 'rotate',
	},
];

export type IconNames = typeof IconsList[number]['name'];
