
export const IconsList = [
	{
		name: 'arrow-up-down',
		preview: 'arrow-down',
		on: 'arrow-down',
		off: 'arrow-up',
	},
	{
		name: 'arrow-left-right',
		preview: 'arrow-left',
		on: 'arrow-left',
		off: 'arrow-right',
	},
	{
		name: 'bath',
		preview: 'bath',
		on: 'bath',
		off: 'bath',
	},
	{
		name: 'circle-plus',
		preview: 'circle-plus',
		on: 'circle-plus',
		off: 'circle-plus',
	},
	{
		name: 'city',
		preview: 'city',
		on: 'city',
		off: 'city',
	},
	{
		name: 'code',
		preview: 'code',
		on: 'code',
		off: 'code',
	},
	{
		name: 'door',
		preview: 'door-closed',
		on: 'door-open',
		off: 'door-closed',
	},
	{
		name: 'gamepad',
		preview: 'gamepad',
		on: 'gamepad',
		off: 'gamepad',
	},
	{
		name: 'gear',
		preview: 'gear',
		on: 'gear',
		off: 'gear',
	},
	{
		name: 'lightbulb',
		preview: 'lightbulb',
		on: 'lightbulb',
		off: 'lightbulb',
	},
	{
		name: 'lock',
		preview: 'lock',
		on: 'lock',
		off: 'unlock',
	},
	{
		name: 'pen',
		preview: 'pen',
		on: 'pen',
		off: 'pen',
	},
	{
		name: 'power',
		preview: 'power-off',
		on: 'power-off',
		off: 'power-off',
	},
	{
		name: 'rocket',
		preview: 'rocket',
		on: 'rocket',
		off: 'rocket',
	},
	{
		name: 'sink',
		preview: 'sink',
		on: 'sink',
		off: 'sink',
	},
	{
		name: 'toggle',
		preview: 'toggle-off',
		on: 'toggle-on',
		off: 'toggle-off',
	},
	{
		name: 'trash-can',
		preview: 'trash-can',
		on: 'trash-can',
		off: 'trash-can',
	},
	{
		name: 'tree',
		preview: 'tree',
		on: 'tree',
		off: 'tree',
	},
	{
		name: 'traingle-exclamation',
		preview: 'triangle-exclamation',
		on: 'triangle-exclamation',
		off: 'triangle-exclamation',
	},
	{
		name: 'tv',
		preview: 'tv',
		on: 'tv',
		off: 'tv',
	},
	{
		name: 'umbrella',
		preview: 'umbrella-beach',
		on: 'umbrella-beach',
		off: 'umbrella-beach',
	},
	{
		name: 'ladder',
		preview: 'water-ladder',
		on: 'water-ladder',
		off: 'water-ladder',
	},
];
